# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddb13c7f20c2a015657ebc293a32b7b5c84951d9cf3009f92f9ab6d98f2377b8591209f5ff1a579ea53b6bbd7c329ff1916c89e4ca311810c348d7785d12b1d0

test:
  secret_key_base: a15ea73b99871ee55685ab66fffeac47af3e0deed40ef0c542e5d0619b61c18e0d55232edd72f29006d634bd3b1026ac2cd75ae4c6880ca43fe037aa6c7295d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
